trigger:
- master

resources:
- repo: self

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'parallo-dockerregistry'
  imageRepository: 'paralloregistry'
  containerRegistry: 'paralloregistry.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  #imagePullSecret: 'aksdevopsacr21364011-auth'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'
  

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          
    - upload: manifests
      artifact: manifests

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build

  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)
    environment: 'dev'
    strategy:
      runOnce:
        deploy:
          steps:
            - task: Bash@3
              inputs:
              targetType: 'inline'
              script: pwd; ls -l
          #steps:
          #- task: KubernetesManifest@0
          #  displayName: Create imagePullSecret
          #  inputs:
           #   action: createSecret
           #   secretName: $(imagePullSecret)
           #   dockerRegistryEndpoint: $(dockerRegistryServiceConnection)
            #- task: KubernetesManifest@0
          #  displayName: list files
          #  inputs:
           #   action: createSecret
           #   secretName: $(imagePullSecret)
           #   dockerRegistryEndpoint: $(dockerRegistryServiceConnection)
              
          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              kubernetesServiceConnection: kubernetes-deploy-connection
              manifests: |
                $(Pipeline.Workspace)/deployment.yml
                $(Pipeline.Workspace)/service.yml
              #imagePullSecrets: |
                #$(imagePullSecret)
              containers: |
                $(containerRegistry)/$(imageRepository):$(tag)